---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jane
  namespace: dev

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jane-dev # Под этим именем увидим созданный RoleBinding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole # К чему привязываемся
  name: admin # имя Role иди ClusterRole к котором мы биндимся
subjects:
  - apiGroup: ""
    kind: ServiceAccount # Указываем к чему привязываемся Role, ServiceAccount
    name: jane
    namespace: dev