---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ken
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: view
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["view"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: RoleBinding-carol # Под этим именем увидим созданный RoleBinding
  namespace: dev
subjects:
  - kind: ServiceAccount # Указываем к чему привязываемся Role, ServiceAccount
    name: ken
    apiGroup: rbac.authorization.k8s.io/v1
roleRef:
  apiGroup: rbac.authorization.k8s.io/v1
  kind: Role # К чему привязываемся
  name: view # имя Role иди ClusterRole к котором мы биндимся