---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ken
  namespace: dev


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: view
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["view"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: RoleBinding-view # Под этим именем увидим созданный RoleBinding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role # К чему привязываемся
  name: view # имя Role иди ClusterRole к котором мы биндимся
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: ServiceAccount # Указываем к чему привязываемся Role, ServiceAccount
    name: system:serviceaccounts:dev
    namespace: dev
