---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carol
  namespace: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: prometheus
  name: edit-prometheus
rules:
  - apiGroups: [""]
    resources: ["pods","services","namespaces","deployments","jobs"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: RoleBinding-carol # Под этим именем увидим созданный RoleBinding
  namespace: prometheus
subjects:
  - kind: ServiceAccount # Указываем к чему привязываемся Role, ServiceAccount
    name: carol
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role # К чему привязываемся
  name: edit-prometheus # имя Role иди ClusterRole к котором мы биндимся