apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: RoleBinding-carol # Под этим именем увидим созданный RoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole # К чему привязываемся
  name: prometheus # имя Role или ClusterRole к котором мы биндимся
subjects:
  - kind: ServiceAccount # Указываем к чему привязываемся Role, ServiceAccount
    name: carol