---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: bob
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin # Под этим именем увидим созданный RoleBinding
  namespace: default
subjects:
  - kind: ServiceAccount # Указываем к чему привязываемся Role, ServiceAccount
    name: bob
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role # К чему привязываемся
  name: bob # имя Role иди ClusterRole к котором мы биндимся
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob
  namespace: default
