apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # namespace не применяется в ClusterRole по понятным причинам
  name: admin
rules:
  - apiGroups: [""] # 1st API group
    resources: ["pods","services","namespaces","deployments","jobs"]
    verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rolebinding:bob-admin

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: ServiceAccount
    name: bob
    namespace: default
