---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: admin
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin # Под этим именем увидим созданный RoleBinding
  namespace: default
subjects:
  - kind: ServiceAccount # Указываем к чему привязываемся Role, ServiceAccount
    name: bob
    apiGroup: rbac.authorization.k8s.io/v1
roleRef:
  apiGroup: rbac.authorization.k8s.io/v1
  kind: Role # К чему привязываемся
  name: admin # имя Role иди ClusterRole к котором мы биндимся
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bob
  namespace: default
